$color = rgba(30, 30, 46, 1)
$inner_color = rgba(30, 30, 46, 0.66)
$outer_color = rgba(20, 20, 31, 1)
$font_color = rgba(0, 0, 0, 1)
$placeholder_color = rgba(0, 0, 0, 0.7)
$check_color = rgba(18, 18, 28, 1)
