

# Faster scroll!
windowrule = scroll_touchpad 1.0, match:class (chromium)

# Overwrite of opac omarchy config
windowrule = opacity 1 1, match:tag chromium-based-browser
windowrule = opacity 1 1, match:tag firefox-based-browser
