
# General Variables
source = ~/.config/hypr/overwrites/looknfeel.conf
source = ~/.config/hypr/overwrites/technicals.conf

#Workspace Definitions and Exeptions
source = ~/.config/hypr/overwrites/plugins.conf
source = ~/.config/hypr/overwrites/monitors.conf
source = ~/.config/hypr/overwrites/workspaces.conf
source = ~/.config/hypr/overwrites/windows.conf

# Input
source = ~/.config/hypr/overwrites/input/input_vars.conf
source = ~/.config/hypr/overwrites/input/app_binds.conf
source = ~/.config/hypr/overwrites/input/tiling.conf
