# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

cursor {
    default_monitor=eDP-1
}
# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
# monitor=eDP-1,2880x1920@120,0x0,2,bitdepth,10 # Some apps dont support Video capture with 10 bit enabled!


# From here on I just use nwg-displays
# monitor=DP-4,2560x1080@200,-640x-1080,1

# Workspace to monitor Binding - Always have 1-4 on Main!!
workspace = 1,monitor:eDP-1
workspace = 2,monitor:eDP-1
workspace = 3,monitor:eDP-1
workspace = 4,monitor:eDP-1
