
render {
    #direct_scanout = 0              # 0/1/2
    #expand_undersized_textures = true
    #xp_mode = false
    #ctm_animation = 2               # 0/1/2
    #cm_fs_passthrough = 2           # 0/1/2
    #cm_enabled = true
    #send_content_type = true
    #cm_auto_hdr = 1                 # 0/1/2
    #new_render_scheduling = false
    #non_shader_cm = 3               # 0/1/2/3
    #cm_sdr_eotf = 0                 # 0/1/2
}

ecosystem {
    #no_update_news = false
    #no_donation_nag = false
    #enforce_permissions = false
}

xwayland {
    enabled = false
    #use_nearest_neighbor = true
    #force_zero_scaling = false
    #create_abstract_socket = false
}

opengl {
    #nvidia_anti_flicker = true
}

experimental {
    #xx_color_management_v4 = false
}

debug {
    #overlay = true
    #damage_blink = false
    #disable_logs = false # Default: True
    #disable_time = true
    #damage_tracking = 2         # 0/1/2
    #enable_stdout_logs = true # Default: False
    #manual_crash = 0
    #suppress_errors = false
    #watchdog_timeout = 5
    #disable_scale_checks = false
    #error_limit = 5
    #error_position = 0          # 0=top,1=bottom
    #colored_stdout_logs = true
    #pass = false
    #full_cm_proto = false
}
