
# === Special Workspace definitions ===
# -- TermWS --
## only ghostty is allowed 👻--
workspace = special:termispace, on-created-empty:ghostty --background-opacity=0.0 --fullscreen --title="termispace-win" -e zsh +new-window
workspace = special:termispace, border:false, shadow:false, rounding:false, decorate:false
windowrule {
  name = windowrule-1
  workspace = +0
  match:workspace = special:termispace
  match:initial_title = negative:^(termispace-win)$
}

windowrule {
  name = windowrule-2
  no_blur = on
  match:initial_title = ^(termispace-win)$
}

bind = SUPER, E, togglespecialworkspace, termispace

# -- Scratchpad --
workspace = special:scratchpad
windowrule {
  name = windowrule-3
  opacity = 0.7 override 0.7 override 0.7 override
  match:workspace = special:scratchpad
}


# -- Todo App (Todoist auf Esc+^ mit Special Functionality, wie TermWS.)
workspace = special:todoistspace, on-created-empty:todoist
workspace = special:todoistspace, border:false, shadow:false, rounding:false, decorate:false
windowrule {
  name = windowrule-4
  workspace = +0
  match:workspace = special:todoistspace
}

windowrule {
  name = windowrule-5
  fullscreen = on
  match:workspace = special:todoistspace
  match:class = ^(Todoist)$
}

bind = SUPER, grave, togglespecialworkspace, todoistspace
