# === Tiling and Workspaces ===
# << focus >>
unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r
unbind = SUPER, TAB
unbind = SUPER SHIFT, TAB
bind = SUPER CTRL, TAB, workspace, previous
bind = SUPER, TAB, workspace, e+1
bind = SUPER SHIFT, TAB, workspace, e-1
unbind = SUPER, A
unbind = SUPER, D
bind = SUPER, A, workspace, e-1
bind = SUPER, D, workspace, e+1
# << move >>
unbind = SUPER CTRL SHIFT 
unbind = SUPER CTRL SHIFT 
unbind = SUPER CTRL SHIFT 
unbind = SUPER CTRL SHIFT 
bind = SUPER CTRL SHIFT, h, swapwindow, l
bind = SUPER CTRL SHIFT, j, swapwindow, d
bind = SUPER CTRL SHIFT, k, swapwindow, u
bind = SUPER CTRL SHIFT, l, swapwindow, r
# << swap >>
unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, L
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, L, movewindow, r
# << resizing >>       
unbind = SUPER CTRL, H
unbind = SUPER CTRL, J
unbind = SUPER CTRL, K
unbind = SUPER CTRL, L
bind = SUPER CTRL, H, resizeactive, -5% 0% 
bind = SUPER CTRL, J, resizeactive, 0% 5%
bind = SUPER CTRL, K, resizeactive, 0% -5%
bind = SUPER CTRL, L, resizeactive, 5% 0%
bindde = SUPER CTRL, H, Expand  window left , resizeactive, -5% 0% 
bindde = SUPER CTRL, J, Shrink window left  , resizeactive, 0% 5%
bindde = SUPER CTRL, K, Shrink window up    , resizeactive, 0% -5%
bindde = SUPER CTRL, L, Expand window down  , resizeactive, 5% 0%
# << groups >>
# (- Mal sehen.)
# <<< gestures >>>
gesture = 3, horizontal, workspace
gesture = 3, vertical, dispatcher,  hyprexpo:expo, toggle
# << Layout Control >>
unbind = SUPER, I
bind = SUPER, I, togglesplit
# << Monitors >>
unbind = SUPER ALT, TAB
bind = SUPER ALT, TAB, focusmonitor, +1 
unbind = SUPER CTRL SHIFT, TAB
bind = SUPER CTRL SHIFT, TAB, movecurrentworkspacetomonitor, +1 
